image: gitpod/workspace-full-vnc
vscode:
  extensions:
    - Dart-Code.flutter
tasks:
  - name: opentofu
    before: |
      brew install opentofu
  - name: gcp-cli
    before: |
      gp sync-await flutter-sdk
      bin/install_gcp-cli.sh
  - name: flutter-sdk
    before: |
      bin/install_flutter-sdk.sh /workspace
      export PATH="/workspace/flutter/bin:$PATH"
      dart pub global activate flutterfire_cli
      export PATH="$PATH":"$HOME/.pub-cache/bin"
      gp sync-done flutter-sdk
  - name: firebase-cli
    before: |
      npm install -g firebase-tools
      