image: gitpod/workspace-full-vnc
vscode:
  extensions:
    - Dart-Code.flutter
tasks:
  - name: opentofu
    before: |
      brew install opentofu
  - name: gcp-cli
    before: |
      gp sync-await flutter-sdk
      bin/install_gcp-cli.sh
  - name: flutter-sdk
    before: |
      bin/install_flutter-sdk.sh /workspace
      export PATH="/workspace/flutter/bin:$PATH"
      gp sync-done flutter-sdk
